@echo off
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whaven.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whtag.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whplr.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whobj.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whinp.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whfx.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whsndmod.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whmenu.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whani.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whnet.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r cdrom.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r whctm.c
wtouch icorp.h
wh

